### ISSUE TITLE
Inquiry about performance of gradmatch

### ISSUE THREAD

**Issue by pipilurj** [decile-team/cords#81]
Hello, I ran some experiments with gradmatch and  randomonline, and  find these two actually reach similar performances after 300 epochs, which is around  93, is there something important to note for reproducing the results? Thanks for your help!

**Comment by krishnatejakk** [comment]
@pipilurj This is because RandomOnline can be a very strong baseline for some datasets and can be difficult to beat in terms of efficiency as GradMatch, CRAIG subset selection steps are computationally expensive. We have explained this issue in more detail and proposed a new subset selection approach that performs even better in the following pre-print: [“MILO: Model-Agnostic Subset Selection Framework for Efficient Model Training and Tuning”](https://arxiv.org/abs/2301.13287)
